[project]
name = "ci-cd-pipline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "pytest>=8.4.1",
    "uvicorn[standard]>=0.35.0",
]

[build-system]
requires = ["uv"]
build-backend = "uv.build"