name: FastAPI CI/CD with uv

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uv and dependencies
      run: |
        curl -Ls https://astral.sh/uv/install.sh | bash
        export PATH="/home/runner/.cargo/bin:$PATH"
        uv pip install --system

    - name: Run tests
      run: |
        pytest || echo "no tests yet"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
          docker stop fastapi-app || true && docker rm fastapi-app || true
          docker run -d --name fastapi-app -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
